host="0.0.0.0"
port=8080

platform-db-url="jdbc:postgresql://localhost:5432/Sandbox"
platform-db-url=${?PLATFORM_DB_URL}

platform-db-user="postgres"
platform-db-user=${?PLATFORM_DB_USER}

platform-db-password="passwd"
platform-db-password=${?PLATFORM_DB_PASSWORD}

bmc.url="https://ctn-operator.api.sportsbook.com/message-feed/api/betstream/acme/v1"
bmc.url=${?BMC_URL}

bmc.schedulerRate= 30
bmc.schedulerRate=${?BMC_SCHEDULER_RATE}

bmc.batchSize= 1000
bmc.batchSize=${?BMC_BATCH_SIZE}

cert.name ="/opt/sportsbook-dev.p12"
cert.name =${?CERT_NAME}

jurisdiction-filtering=true
jurisdiction-filtering=${?JURISDICTION_FILTERING}

jurisdiction ="US_MICHIGAN,US_PENNSYLVANIA"
jurisdiction =${?JURISDICTION}

start-from = 0
start-from =${?START_FROM}

numThreads = 1
numThreads =${?NUM_THREADS}

maximumPoolSize = 1
maximumPoolSize =${?MAXIMUM_POOL_SIZE}

maxLifetime = 0
maxLifetime =${?MAX_LIFE_TIME}

databases {
   platform {
      profile: "sportsbook.ledger.JsonPostgresProfile$"
      db {
       driver : "org.postgresql.Driver"
       url: ${platform-db-url}
       user: ${platform-db-user}
       password: ${platform-db-password}
       numThreads: ${numThreads}
       maximumPoolSize: ${maximumPoolSize}
       maxLifetime: ${maxLifetime}
      }
   }
}

bmc {
    url: ${bmc.url}
    schedulerRate: ${bmc.schedulerRate}
    httpTimeout: 10000
    batchSize: ${bmc.batchSize}
}

# Monitoring
kamon {

  environment {
    service = "sportsbook-ledger"
    tags {
      state = "XX"
      state = ${?DATA_DOG_MONITORING_STATE}
      env = DEV
      env = ${?ENV}
      brand = ACME
      brand = ${?BRAND}
    }
  }

  modules {
    datadog-agent {
      enabled = false
      enabled = ${?KAMON_MODULES_DATADOG_AGENT_ENABLED}
    }

    datadog-trace-agent {
      enabled = false
      enabled = ${?KAMON_MODULES_DATADOG_TRACE_AGENT_ENABLED}
    }

    datadog-api {
      enabled = false
      enabled = ${?KAMON_MODULES_DATADOG_API_ENABLED}
    }

    host-metrics {
      enabled = no
    }
  }

  datadog {

    #
    # Settings relevant to the DatadogAgentReporter
    #
    agent {

      # Hostname and port in which your dogstatsd is running (if not using
      # the API). Remember that Datadog packets are sent using UDP and
      # setting unreachable hosts and/or not open ports wont be warned
      # by the Kamon, your data wont go anywhere.
      hostname = "localhost"
      hostname = ${?DATA_DOG_AGENT_HOSTAME}
      port = 8125

      # Max packet size for UDP metrics data sent to Datadog.
      max-packet-size = 1024 bytes
      measurement-formatter = "default"
      packetbuffer = "default"
    }

    metric {
      # Interval at which metric snapshots will be collected and sent to all metric reporters.
      tick-interval = 5 second
    }
    #
    # Settings relevant to the DatadogSpanReporter
    #
    trace {

      # Default to trace agent URL
      # See: (https://docs.datadoghq.com/api/?lang=python#tracing)
      api-url = "http://"${kamon.datadog.agent.hostname}":8126/v0.4/traces"

      # FQCN of the "kamon.datadog.KamonDataDogTranslator" implementation
      # that will convert Kamon Spans into Datadog Spans, or "defult" to
      # use the built-in translator.
      translator = "default"

      # HTTP client timeout settings:
      #   - connect-timeout: how long to wait for an HTTP connection
      #     to establish before failing the request.
      #   - read-timeout: how long to wait for a read IO operation
      #     to complete before failing the request.
      #   - write-timeout: how long to wait for a write IO operation
      #     to complete before failing the request.
      #
      connect-timeout = 5 seconds
      read-timeout = 5 seconds
      write-timeout = 5 seconds
    }
  }
}
