# Companion code for "The Backend of Luck" - Chapter 31, Performance Benchmarks and Metrics.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: casino-service-hpa
  namespace: casino-prod
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 120
    scaleUp:
      policies:
      - periodSeconds: 30
        type: Pods
        value: 5
      selectPolicy: Max
      stabilizationWindowSeconds: 30
  maxReplicas: 50
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: casino-service
