# Companion code for "The Backend of Luck" - Chapter 10, Complete Platform Architecture.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

"""
gameservice.models.enums — Categorical Domain Values
=====================================================

All categorical values in the domain are represented as Python ``Enum`` sub-
classes.  This prevents stringly-typed bugs, enables IDE auto-complete, and
makes exhaustiveness checking possible with tools like ``mypy``.

Naming convention
-----------------
* Enum *class* names are ``PascalCase`` nouns or noun-phrases.
* Enum *member* names are ``UPPER_SNAKE_CASE``.
"""

from __future__ import annotations

from enum import Enum, unique


@unique
class GameMode(str, Enum):
    """The financial mode in which a game session is launched.

    ``REAL_MONEY``
        Player wagers real funds; all transactions hit the live wallet.
    ``DEMO``
        Play-money session; no real transactions are created.  Not all
        jurisdictions permit demo mode (see :class:`JurisdictionProfile`).
    ``FREE_ROUND``
        A bonus-funded session where the supplier credits winnings back to
        the wallet; no player debit occurs.
    """

    REAL_MONEY = "real_money"
    DEMO = "demo"
    FREE_ROUND = "free_round"


@unique
class CommandType(str, Enum):
    """The type of wallet operation requested within a game round.

    ``DEBIT``
        Take funds from the player's wallet (a "wager" or "bet placement").
    ``CREDIT``
        Return funds to the player's wallet (a "win" or "payout").
    ``ROLLBACK``
        Reverse a previously-submitted debit, typically because a game round
        was interrupted before settlement.
    ``ADJUST``
        A platform-originated correction; e.g. bonus wagering contribution
        adjustment or jackpot top-up.
    ``TIP``
        Live-casino dealer tip; treated as a debit with no round association.
    """

    DEBIT = "debit"
    CREDIT = "credit"
    ROLLBACK = "rollback"
    ADJUST = "adjust"
    TIP = "tip"


@unique
class ActionCode(str, Enum):
    """Fine-grained classification of a :class:`RoundCommand`.

    Suppliers include this code so the platform can apply correct wagering-
    contribution rates, track jackpot eligibility, and report correctly to
    regulators.

    ``REGULAR``    — Standard wager or win.
    ``FREE_SPIN``  — Wager / win generated by a free-spin award.
    ``BONUS_BUY``  — Player purchased a bonus feature directly.
    ``JACKPOT``    — Jackpot contribution or jackpot win credit.
    ``RESPIN``     — Re-spin feature wager.
    ``GAMBLE``     — Post-win gamble feature.
    """

    REGULAR = "regular"
    FREE_SPIN = "free_spin"
    BONUS_BUY = "bonus_buy"
    JACKPOT = "jackpot"
    RESPIN = "respin"
    GAMBLE = "gamble"


@unique
class ProductType(str, Enum):
    """Broad category of game product offered by a supplier."""

    SLOTS = "slots"
    LIVE_CASINO = "live_casino"
    SPORTSBOOK = "sportsbook"
    TABLE_GAMES = "table_games"
    VIRTUAL_SPORTS = "virtual_sports"
    SCRATCH_CARDS = "scratch_cards"
    BINGO = "bingo"
    POKER = "poker"


@unique
class CallbackStyle(str, Enum):
    """The integration model used by a supplier for wallet callbacks.

    ``PULL``
        The platform holds the canonical wallet; the supplier queries balances
        via REST before and after each round.
    ``PUSH``
        The supplier pushes wallet events to the platform's webhook endpoints.
    ``SEAMLESS``
        The supplier's backend calls the platform wallet API in real-time for
        every debit and credit (the most common model for modern suppliers).
    """

    PULL = "pull"
    PUSH = "push"
    SEAMLESS = "seamless"


@unique
class FundSource(str, Enum):
    """The funding source to draw from when applying a player debit.

    Used by :class:`~acmetocasino.gameservice.accounts.balance_policy.BalancePolicy`
    to determine usage order.
    """

    CASH = "cash"
    BONUS = "bonus"
    FREE_ROUND_CREDIT = "free_round_credit"


@unique
class RealityCheckAction(str, Enum):
    """The player's response to a reality-check prompt.

    ``CONTINUE``   — Player acknowledged the prompt and wishes to keep playing.
    ``TAKE_BREAK`` — Player chose to end the session.
    ``SET_LIMIT``  — Player chose to navigate to the responsible-gaming page.
    """

    CONTINUE = "continue"
    TAKE_BREAK = "take_break"
    SET_LIMIT = "set_limit"


__all__ = [
    "ActionCode",
    "CallbackStyle",
    "CommandType",
    "FundSource",
    "GameMode",
    "ProductType",
    "RealityCheckAction",
]
