# Companion code for "The Backend of Luck" - Chapter 22, Internal Docker Registry.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

# =============================================================================
# Chapter 37: Internal Docker Registry - Kubernetes Infrastructure
# =============================================================================
# Registry deployments with Harbor, security scanning, and monitoring.
#
# Components:
# - Harbor Registry (enterprise-grade registry)
# - Trivy Scanner (vulnerability scanning)
# - Registry UI (web interface)
# - Prometheus/Grafana monitoring
# =============================================================================

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.11"
    }
  }
}

# =============================================================================
# Variables
# =============================================================================

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "registry-igaming"
}

variable "namespace" {
  description = "Kubernetes namespace"
  type        = string
  default     = "registry"
}

variable "storage_class" {
  description = "Storage class for PVCs"
  type        = string
  default     = "gp3"
}

variable "registry_replicas" {
  description = "Number of registry replicas"
  type        = number
  default     = 2
}

variable "s3_bucket" {
  description = "S3 bucket for storage"
  type        = string
}

variable "redis_endpoint" {
  description = "Redis endpoint"
  type        = string
}

variable "admin_password" {
  description = "Admin password"
  type        = string
  sensitive   = true
}

# =============================================================================
# Namespace
# =============================================================================

resource "kubernetes_namespace" "registry" {
  metadata {
    name = var.namespace

    labels = {
      name       = var.namespace
      project    = var.project_name
      compliance = "pci-dss"
    }
  }
}

# =============================================================================
# ConfigMaps
# =============================================================================

resource "kubernetes_config_map" "registry_config" {
  metadata {
    name      = "registry-config"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  data = {
    "config.yml" = yamlencode({
      version = "0.1"
      log = {
        level     = "info"
        formatter = "json"
      }
      storage = {
        s3 = {
          region = "eu-west-1"
          bucket = var.s3_bucket
          secure = true
          v4auth = true
        }
        cache = {
          blobdescriptor = "redis"
        }
        maintenance = {
          uploadpurging = {
            enabled  = true
            age      = "168h"
            interval = "24h"
          }
        }
        delete = {
          enabled = true
        }
      }
      redis = {
        addr = "${var.redis_endpoint}:6379"
        db   = 0
      }
      http = {
        addr = "0.0.0.0:5000"
        headers = {
          "X-Content-Type-Options" = ["nosniff"]
        }
      }
      health = {
        storagedriver = {
          enabled   = true
          interval  = "10s"
          threshold = 3
        }
      }
    })

    "trivy-config.yml" = yamlencode({
      cache = {
        dir = "/home/scanner/.cache"
      }
      severity = ["CRITICAL", "HIGH", "MEDIUM"]
      scanners = ["vuln", "secret", "config"]
      timeout  = "10m"
    })
  }
}

# =============================================================================
# Secrets
# =============================================================================

resource "kubernetes_secret" "registry_auth" {
  metadata {
    name      = "registry-auth"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  type = "Opaque"

  data = {
    "htpasswd" = "" # Generated by init container
  }

  lifecycle {
    ignore_changes = [data]
  }
}

resource "kubernetes_secret" "registry_tls" {
  metadata {
    name      = "registry-tls"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  type = "kubernetes.io/tls"

  data = {
    "tls.crt" = ""
    "tls.key" = ""
  }

  lifecycle {
    ignore_changes = [data]
  }
}

# =============================================================================
# Service Account
# =============================================================================

resource "kubernetes_service_account" "registry" {
  metadata {
    name      = "registry"
    namespace = kubernetes_namespace.registry.metadata[0].name

    annotations = {
      "eks.amazonaws.com/role-arn" = "arn:aws:iam::ACCOUNT_ID:role/registry-s3-role"
    }
  }
}

# =============================================================================
# Registry Deployment
# =============================================================================

resource "kubernetes_deployment" "registry" {
  metadata {
    name      = "registry"
    namespace = kubernetes_namespace.registry.metadata[0].name

    labels = {
      app     = "registry"
      project = var.project_name
    }
  }

  spec {
    replicas = var.registry_replicas

    selector {
      match_labels = {
        app = "registry"
      }
    }

    strategy {
      type = "RollingUpdate"
      rolling_update {
        max_surge       = "1"
        max_unavailable = "0"
      }
    }

    template {
      metadata {
        labels = {
          app     = "registry"
          project = var.project_name
        }

        annotations = {
          "prometheus.io/scrape" = "true"
          "prometheus.io/port"   = "5001"
        }
      }

      spec {
        service_account_name = kubernetes_service_account.registry.metadata[0].name

        affinity {
          pod_anti_affinity {
            preferred_during_scheduling_ignored_during_execution {
              weight = 100
              pod_affinity_term {
                label_selector {
                  match_labels = {
                    app = "registry"
                  }
                }
                topology_key = "topology.kubernetes.io/zone"
              }
            }
          }
        }

        security_context {
          run_as_non_root = true
          run_as_user     = 1000
          fs_group        = 1000
          seccomp_profile {
            type = "RuntimeDefault"
          }
        }

        container {
          name              = "registry"
          image             = "registry:2.8"
          image_pull_policy = "IfNotPresent"

          port {
            name           = "http"
            container_port = 5000
          }

          port {
            name           = "metrics"
            container_port = 5001
          }

          env {
            name  = "REGISTRY_HTTP_DEBUG_ADDR"
            value = "0.0.0.0:5001"
          }

          env {
            name  = "REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED"
            value = "true"
          }

          resources {
            requests = {
              cpu    = "200m"
              memory = "256Mi"
            }
            limits = {
              cpu    = "1000m"
              memory = "1Gi"
            }
          }

          liveness_probe {
            http_get {
              path = "/v2/"
              port = 5000
            }
            initial_delay_seconds = 10
            period_seconds        = 10
            failure_threshold     = 3
          }

          readiness_probe {
            http_get {
              path = "/v2/"
              port = 5000
            }
            initial_delay_seconds = 5
            period_seconds        = 5
            failure_threshold     = 3
          }

          volume_mount {
            name       = "config"
            mount_path = "/etc/docker/registry"
            read_only  = true
          }

          security_context {
            allow_privilege_escalation = false
            read_only_root_filesystem  = true
            capabilities {
              drop = ["ALL"]
            }
          }
        }

        volume {
          name = "config"
          config_map {
            name = kubernetes_config_map.registry_config.metadata[0].name
            items {
              key  = "config.yml"
              path = "config.yml"
            }
          }
        }
      }
    }
  }
}

# =============================================================================
# Trivy Scanner Deployment
# =============================================================================

resource "kubernetes_deployment" "trivy_scanner" {
  metadata {
    name      = "trivy-scanner"
    namespace = kubernetes_namespace.registry.metadata[0].name

    labels = {
      app     = "trivy-scanner"
      project = var.project_name
    }
  }

  spec {
    replicas = 2

    selector {
      match_labels = {
        app = "trivy-scanner"
      }
    }

    template {
      metadata {
        labels = {
          app     = "trivy-scanner"
          project = var.project_name
        }
      }

      spec {
        security_context {
          run_as_non_root = true
          run_as_user     = 1000
          fs_group        = 1000
        }

        container {
          name              = "trivy"
          image             = "aquasec/trivy:latest"
          image_pull_policy = "IfNotPresent"

          args = ["server", "--listen", "0.0.0.0:8080"]

          port {
            name           = "http"
            container_port = 8080
          }

          env {
            name  = "TRIVY_CACHE_DIR"
            value = "/home/scanner/.cache"
          }

          resources {
            requests = {
              cpu    = "100m"
              memory = "256Mi"
            }
            limits = {
              cpu    = "500m"
              memory = "1Gi"
            }
          }

          liveness_probe {
            http_get {
              path = "/healthz"
              port = 8080
            }
            initial_delay_seconds = 30
            period_seconds        = 30
          }

          volume_mount {
            name       = "cache"
            mount_path = "/home/scanner/.cache"
          }

          security_context {
            allow_privilege_escalation = false
            read_only_root_filesystem  = true
            capabilities {
              drop = ["ALL"]
            }
          }
        }

        volume {
          name = "cache"
          empty_dir {
            size_limit = "2Gi"
          }
        }
      }
    }
  }
}

# =============================================================================
# Services
# =============================================================================

resource "kubernetes_service" "registry" {
  metadata {
    name      = "registry"
    namespace = kubernetes_namespace.registry.metadata[0].name

    labels = {
      app = "registry"
    }
  }

  spec {
    type = "ClusterIP"

    selector = {
      app = "registry"
    }

    port {
      name        = "http"
      port        = 5000
      target_port = 5000
    }

    port {
      name        = "metrics"
      port        = 5001
      target_port = 5001
    }
  }
}

resource "kubernetes_service" "trivy" {
  metadata {
    name      = "trivy-scanner"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  spec {
    type = "ClusterIP"

    selector = {
      app = "trivy-scanner"
    }

    port {
      port        = 8080
      target_port = 8080
    }
  }
}

# =============================================================================
# Horizontal Pod Autoscaler
# =============================================================================

resource "kubernetes_horizontal_pod_autoscaler_v2" "registry" {
  metadata {
    name      = "registry-hpa"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  spec {
    scale_target_ref {
      api_version = "apps/v1"
      kind        = "Deployment"
      name        = kubernetes_deployment.registry.metadata[0].name
    }

    min_replicas = 2
    max_replicas = 10

    metric {
      type = "Resource"
      resource {
        name = "cpu"
        target {
          type                = "Utilization"
          average_utilization = 70
        }
      }
    }

    behavior {
      scale_down {
        stabilization_window_seconds = 300
      }
    }
  }
}

# =============================================================================
# Pod Disruption Budget
# =============================================================================

resource "kubernetes_pod_disruption_budget" "registry" {
  metadata {
    name      = "registry-pdb"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  spec {
    min_available = "1"

    selector {
      match_labels = {
        app = "registry"
      }
    }
  }
}

# =============================================================================
# Network Policy
# =============================================================================

resource "kubernetes_network_policy" "registry" {
  metadata {
    name      = "registry-network-policy"
    namespace = kubernetes_namespace.registry.metadata[0].name
  }

  spec {
    pod_selector {
      match_labels = {
        app = "registry"
      }
    }

    policy_types = ["Ingress", "Egress"]

    ingress {
      from {
        namespace_selector {
          match_labels = {
            name = "ingress-nginx"
          }
        }
      }
      ports {
        port     = 5000
        protocol = "TCP"
      }
    }

    ingress {
      from {
        namespace_selector {
          match_labels = {
            name = "monitoring"
          }
        }
      }
      ports {
        port     = 5001
        protocol = "TCP"
      }
    }

    egress {
      to {
        ip_block {
          cidr = "0.0.0.0/0"
        }
      }
      ports {
        port     = 443
        protocol = "TCP"
      }
      ports {
        port     = 6379
        protocol = "TCP"
      }
    }

    egress {
      ports {
        port     = 53
        protocol = "UDP"
      }
    }
  }
}

# =============================================================================
# Ingress
# =============================================================================

resource "kubernetes_ingress_v1" "registry" {
  metadata {
    name      = "registry-ingress"
    namespace = kubernetes_namespace.registry.metadata[0].name

    annotations = {
      "kubernetes.io/ingress.class"                    = "nginx"
      "nginx.ingress.kubernetes.io/ssl-redirect"       = "true"
      "nginx.ingress.kubernetes.io/proxy-body-size"    = "0"
      "nginx.ingress.kubernetes.io/proxy-read-timeout" = "600"
      "cert-manager.io/cluster-issuer"                 = "letsencrypt-prod"
    }
  }

  spec {
    tls {
      hosts       = ["registry.igaming.example.com"]
      secret_name = "registry-tls"
    }

    rule {
      host = "registry.igaming.example.com"

      http {
        path {
          path      = "/"
          path_type = "Prefix"

          backend {
            service {
              name = kubernetes_service.registry.metadata[0].name
              port {
                number = 5000
              }
            }
          }
        }
      }
    }
  }
}

# =============================================================================
# Outputs
# =============================================================================

output "namespace" {
  description = "Registry namespace"
  value       = kubernetes_namespace.registry.metadata[0].name
}

output "registry_service" {
  description = "Registry service name"
  value       = kubernetes_service.registry.metadata[0].name
}

output "trivy_service" {
  description = "Trivy scanner service name"
  value       = kubernetes_service.trivy.metadata[0].name
}
