# openbao-cloudhsm.hcl — OpenBao server configuration template
# Node: bao-01 (CloudHSM PKCS#11 auto-unseal)
# Replace placeholder values with node-specific settings before deploying.
#
# CloudHSM equivalent of:
#   ../yubihsm-setup/openbao.hcl
#
# Key differences from YubiHSM 2 configuration:
#   - lib: /opt/cloudhsm/lib/libcloudhsm_pkcs11.so (not yubihsm_pkcs11.so)
#   - slot: "1" (CloudHSM presents slot 1 by default; YubiHSM uses slot 0)
#   - mechanism: 0x00001085 = CKM_AES_KEY_WRAP_PAD (PKCS#5 padding; YubiHSM uses CKM_AES_GCM 0x1087)
#   - key_label: "wrap-key-aes256" (generated by setup-cloudhsm-cluster.sh)
#   - PIN: set via CLOUDHSM_PIN environment variable (format: hsm-app:<password>)
#   - CloudHSM client daemon (cloudhsm-client) must be running before OpenBao starts
#
# References:
#   - OpenBao PKCS#11 seal: https://openbao.org/docs/configuration/seal/pkcs11/
#   - CloudHSM PKCS#11: https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-mechanisms.html
#   - PCI DSS v4.0.1 Req. 3.5, 3.6, 3.7
#   - FIPS 140-2 Level 3 (CloudHSM — Luna Network HSM 7)

# ── Global settings ───────────────────────────────────────────────────────────
ui             = true
disable_mlock  = false      # MUST be false in production — prevents RAM swap of secrets
log_level      = "info"
log_format     = "json"     # Structured logging — required for SIEM integration

# ── Raft integrated storage ───────────────────────────────────────────────────
# No external Consul dependency. 3-node cluster for 99.95% availability.
storage "raft" {
  path    = "/opt/openbao/data"
  node_id = "bao-01"  # CHANGE per node: bao-01 | bao-02 | bao-03

  # Retry-join: cluster members automatically discover and join the leader
  # Replace IPs with your OpenBao EC2 instance private IPs (or NLB targets)
  retry_join {
    leader_api_addr         = "https://10.0.2.10:8200"  # CHANGE bao-02 IP
    leader_ca_cert_file     = "/opt/openbao/tls/ca.crt"
    leader_client_cert_file = "/opt/openbao/tls/bao-01.crt"   # CHANGE per node
    leader_client_key_file  = "/opt/openbao/tls/bao-01.key"   # CHANGE per node
  }
  retry_join {
    leader_api_addr         = "https://10.0.3.10:8200"  # CHANGE bao-03 IP
    leader_ca_cert_file     = "/opt/openbao/tls/ca.crt"
    leader_client_cert_file = "/opt/openbao/tls/bao-01.crt"   # CHANGE per node
    leader_client_key_file  = "/opt/openbao/tls/bao-01.key"   # CHANGE per node
  }

  # Performance tuning for iGaming workload
  performance_multiplier = 1
}

# ── TLS listener ──────────────────────────────────────────────────────────────
# TLS 1.3 minimum — PCI DSS Req. 4
listener "tcp" {
  address            = "0.0.0.0:8200"
  tls_cert_file      = "/opt/openbao/tls/bao-01.crt"   # CHANGE per node
  tls_key_file       = "/opt/openbao/tls/bao-01.key"   # CHANGE per node
  tls_client_ca_cert = "/opt/openbao/tls/ca.crt"
  tls_min_version    = "tls13"

  # Enable mTLS once all services have PKI-issued certs:
  # tls_require_and_verify_client_cert = true
}

# ── PKCS#11 auto-unseal via AWS CloudHSM ─────────────────────────────────────
#
# OpenBao 2.2+ OSS — PKCS#11 seal is available without Enterprise licence.
# The wrap key (wrap-key-aes256) lives ONLY in CloudHSM hardware.
# CKM_AES_KEY_WRAP_PAD (0x00001085) is used to wrap the barrier key.
#
# MECHANISM NOTES:
#   0x00001085 = CKM_AES_KEY_WRAP_PAD  — recommended for AES key wrapping
#   0x00001087 = CKM_AES_GCM           — alternative, used in YubiHSM setup
#   CKM_AES_KEY_WRAP_PAD is preferred with CloudHSM as it uses PKCS#5 padding
#   and does not require a separate IV/nonce management.
#
# SLOT NOTE:
#   CloudHSM presents a single virtual slot (slot 1 by default).
#   Verify with: /opt/cloudhsm/bin/key_mgmt_util — listSlots
#
# PIN FORMAT:
#   CloudHSM CU credentials: "<username>:<password>"
#   Example: "hsm-app:MySecurePassword123"
#   NEVER store the PIN in this file — inject via systemd drop-in:
#   /etc/systemd/system/openbao.service.d/hsm.conf (chmod 600)
#
# KEY MUST EXIST before starting OpenBao.
# If generate_key = "true", OpenBao will attempt to create the key on first start.
# For production, pre-generate the key with setup-cloudhsm-cluster.sh.
seal "pkcs11" {
  lib          = "/opt/cloudhsm/lib/libcloudhsm_pkcs11.so"
  slot         = "1"
  pin          = "env:CLOUDHSM_PIN"
  key_label    = "wrap-key-aes256"
  mechanism    = "0x00001085"   # CKM_AES_KEY_WRAP_PAD
  generate_key = "false"        # pre-generated; set "true" only for first-time setup
}

# ── Cluster addresses ─────────────────────────────────────────────────────────
# api_addr: advertised to clients and peer nodes
# cluster_addr: Raft replication port
api_addr     = "https://10.0.1.10:8200"    # CHANGE: this node's private IP
cluster_addr = "https://10.0.1.10:8201"    # CHANGE: this node's private IP

# ── Telemetry — Prometheus metrics for CloudWatch and Grafana ─────────────────
# Exposes /v1/sys/metrics for Prometheus scraping
# On AWS, use the CloudWatch agent to forward these metrics
telemetry {
  prometheus_retention_time = "60s"
  disable_hostname          = false
}
