---
# Companion code for "The Backend of Luck" - Chapter 23, DevSecOps for iGaming.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

server_net: 10.100.0.0/16
ipmi_net: 172.20.100.0/24
vpn_net: 192.168.100.0/24

dd_site_tags:
  env: acme-prod
  environment: PROD
  environment_name: LIVE
  brand: ACME
  infra: C8
  country: US
  state: PA
  vendor: ACME
  jurisdiction: us-pa

dd_checks:
  raidcheck:
    init_config:
    instances:
      [{}]
  ipmicheck:
    init_config:
    instances:
      [{}]
  journald:
    logs:
      - type: journald
        path: /var/log/journal/
        include_units:
          - ipmievd.service
          - ipmiseld.service
          - docker.service
          - sshd.service
  docker:
    init_config:
    instances:
      - url: "unix://var/run/docker.sock"
        new_tag_names: true
