
db.host = prod-db.acmetocasino-internal.example.com
db.host = ${?DB_HOST}
db.default.driver = org.postgresql.Driver
db.default.url = "jdbc:postgresql://"${db.host}":5432/platform_db"
db.default.user = platform_sync
db.default.user = ${?DB_USER}
db.default.password = ${?DB_PASS}

scalikejdbc.global.loggingSQLAndTime.enabled=true
scalikejdbc.global.loggingSQLAndTime.logLevel=info
scalikejdbc.global.loggingSQLAndTime.warningEnabled=true
scalikejdbc.global.loggingSQLAndTime.warningThresholdMillis=1000
scalikejdbc.global.loggingSQLAndTime.warningLogLevel=warn
scalikejdbc.global.loggingSQLAndTime.singleLineMode=true
scalikejdbc.global.loggingSQLAndTime.printUnprocessedStackTrace=false
scalikejdbc.global.loggingSQLAndTime.stackTraceDepth=10

etsync {
  sftpHost = sftp.marketingcloudops.example.com
  sftpImportDir = Import
  sftpExportDir = Export

  lastSyncedFile = lastSynced.txt
  csvDirectory = to-export

  sftpPlayersImportDir = ${etsync.sftpImportDir}/subscribers-sync
}

dataExtensionClients = [{
    brandName = "AcmetoCasino Brand A"
    clientId = ${?ET_CLIENT_ID_BRAND_A}
    clientSecret = ${?ET_CLIENT_SECRET_BRAND_A}
    soapEndpoint = "https://tenant.soap.marketingcloudapis.com"
    authEndpoint = "https://tenant.auth.marketingcloudapis.com"
},{
    brandName = "AcmetoCasino Brand B"
    clientId = ${?ET_CLIENT_ID_BRAND_B}
    clientSecret = ${?ET_CLIENT_SECRET_BRAND_B}
    soapEndpoint = "https://tenant.soap.marketingcloudapis.com"
    authEndpoint = "https://tenant.auth.marketingcloudapis.com"
},{
    brandName = "AcmetoCasino Brand C"
    clientId = ${?ET_CLIENT_ID_BRAND_C}
    clientSecret = ${?ET_CLIENT_SECRET_BRAND_C}
    soapEndpoint = "https://tenant.soap.marketingcloudapis.com"
    authEndpoint = "https://tenant.auth.marketingcloudapis.com"
}]

ops-genie-api-key=${?OPS_GENIE_API_KEY}

send-alerts=true
send-alerts=${?SEND_ALERTS}
