// Companion code for "The Backend of Luck" - Chapter 46, Building a Brazilian Betting Platform.
// https://thebackendofluck.com | https://github.com/thebackendofluck/book
// SPDX-License-Identifier: Apache-2.0
//
// FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
// Published to demonstrate the patterns explained in the book. This code is
// not certified for real-money gaming: operating a gambling platform requires
// your own licence, independent test-lab certification (GLI, eCOGRA or
// equivalent) and regulator approval.

package main

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
)

// ErrInsufficientFunds is returned when a debit would result in a negative balance.
var ErrInsufficientFunds = errors.New("insufficient funds")

// ErrWalletBlocked is returned when a wallet operation is attempted on a blocked account.
var ErrWalletBlocked = errors.New("wallet is blocked")

// PIXClient handles PIX payment initiation, confirmation, and payout.
// In production this wraps a PSP (e.g., Itaú, Bradesco, Gerencianet) API.
type PIXClient struct {
	store      *Store
	pspBaseURL string
	pspAPIKey  string
	merchantCPFCNPJ string
	logger     *slog.Logger
}

// NewPIXClient creates a new PIXClient.
func NewPIXClient(store *Store, pspBaseURL, pspAPIKey, merchantCPFCNPJ string, logger *slog.Logger) *PIXClient {
	return &PIXClient{
		store:           store,
		pspBaseURL:      pspBaseURL,
		pspAPIKey:       pspAPIKey,
		merchantCPFCNPJ: merchantCPFCNPJ,
		logger:          logger,
	}
}

// InitiateDeposit creates a PIX QR code for the player to pay.
// Returns the PIXPayment with QR code data.
func (c *PIXClient) InitiateDeposit(ctx context.Context, cpf string, amount float64) (*PIXPayment, error) {
	if amount < 1.00 {
		return nil, fmt.Errorf("minimum deposit is R$1.00")
	}
	if amount > 50000.00 {
		return nil, fmt.Errorf("maximum single deposit is R$50,000.00")
	}

	pixID := uuid.NewString()
	now := time.Now().UTC()
	expiresAt := now.Add(30 * time.Minute)

	// Generate a deterministic transaction ID for the QR code.
	txID := generateTxID()

	// Build the PIX Copia e Cola (BR Code) string.
	// In production this is generated by the PSP API.
	copyPaste := buildBRCode(c.merchantCPFCNPJ, amount, txID)

	p := &PIXPayment{
		ID:            pixID,
		CPF:           cpf,
		Type:          "deposit",
		Amount:        amount,
		Status:        PIXStatusPending,
		QRCode:        fmt.Sprintf("https://pix.qr/%s", txID), // stub URL
		QRCodeBase64:  generateQRCodeBase64Stub(copyPaste),
		CopyPasteCode: copyPaste,
		ExpiresAt:     expiresAt,
		CreatedAt:     now,
		UpdatedAt:     now,
	}

	if err := c.store.CreatePIXPayment(ctx, p); err != nil {
		return nil, fmt.Errorf("create pix payment: %w", err)
	}

	c.logger.Info("pix deposit initiated",
		"pix_id", pixID,
		"cpf", maskCPF(cpf),
		"amount", amount,
	)
	return p, nil
}

// InitiateWithdrawal creates a PIX withdrawal (payout) request.
// Debits the wallet immediately and sends the transfer to the PSP.
func (c *PIXClient) InitiateWithdrawal(ctx context.Context, cpf string, req *WithdrawRequest) (*PIXPayment, error) {
	if req.Amount < 10.00 {
		return nil, fmt.Errorf("minimum withdrawal is R$10.00")
	}
	if req.Amount > 20000.00 {
		return nil, fmt.Errorf("maximum single withdrawal is R$20,000.00")
	}
	if req.PixKey == "" {
		return nil, fmt.Errorf("pix_key is required for withdrawal")
	}

	// Verify closed payment loop: the PIX key must match the registered CPF
	// or a pre-verified bank account (Portaria 615/2024, Art. 14).
	if err := c.verifyClosedLoop(ctx, cpf, req.PixKey, req.PixKeyType); err != nil {
		return nil, fmt.Errorf("closed loop check: %w", err)
	}

	pixID := uuid.NewString()
	now := time.Now().UTC()

	// Debit wallet first (prevents over-withdrawal).
	debitTx := &Transaction{
		ID:          uuid.NewString(),
		CPF:         cpf,
		Type:        TxTypeWithdrawal,
		Amount:      req.Amount,
		ReferenceID: pixID,
		Description: "PIX withdrawal",
	}
	if err := c.store.Debit(ctx, cpf, req.Amount, debitTx); err != nil {
		if errors.Is(err, ErrInsufficientFunds) {
			return nil, fmt.Errorf("insufficient funds: balance too low for R$%.2f withdrawal", req.Amount)
		}
		return nil, fmt.Errorf("debit wallet: %w", err)
	}

	p := &PIXPayment{
		ID:          pixID,
		CPF:         cpf,
		Type:        "withdrawal",
		Amount:      req.Amount,
		Status:      PIXStatusPending,
		PixKey:      req.PixKey,
		ExpiresAt:   now.Add(24 * time.Hour),
		CreatedAt:   now,
		UpdatedAt:   now,
	}

	if err := c.store.CreatePIXPayment(ctx, p); err != nil {
		return nil, fmt.Errorf("create pix payment: %w", err)
	}

	c.logger.Info("pix withdrawal initiated",
		"pix_id", pixID,
		"cpf", maskCPF(cpf),
		"amount", req.Amount,
		"pix_key", req.PixKey,
	)

	return p, nil
}

// ConfirmDeposit processes a webhook confirmation from the PSP.
// Idempotent: calling it twice for the same PIX ID is safe.
func (c *PIXClient) ConfirmDeposit(ctx context.Context, webhook *PIXWebhookPayload) error {
	pix, err := c.store.GetPIXPayment(ctx, webhook.PIXPaymentID)
	if err != nil {
		return fmt.Errorf("get pix payment: %w", err)
	}
	if pix.Status == PIXStatusConfirmed {
		c.logger.Info("pix deposit already confirmed (idempotent)", "pix_id", webhook.PIXPaymentID)
		return nil
	}
	if time.Now().UTC().After(pix.ExpiresAt) {
		return fmt.Errorf("pix payment %s has expired", webhook.PIXPaymentID)
	}
	if abs(pix.Amount-webhook.Amount) > 0.01 {
		return fmt.Errorf("amount mismatch: expected %.2f, got %.2f", pix.Amount, webhook.Amount)
	}

	if err := c.store.ConfirmPIXDeposit(ctx, pix.ID, webhook.E2EID, pix.Amount, pix.CPF); err != nil {
		return fmt.Errorf("confirm pix deposit: %w", err)
	}

	c.logger.Info("pix deposit confirmed",
		"pix_id", pix.ID,
		"e2e_id", webhook.E2EID,
		"cpf", maskCPF(pix.CPF),
		"amount", pix.Amount,
	)
	return nil
}

// verifyClosedLoop enforces Portaria 615/2024 closed payment loop rules.
// A player may only withdraw to a CPF-keyed account matching their own,
// or a pre-registered and verified bank account.
func (c *PIXClient) verifyClosedLoop(ctx context.Context, cpf, pixKey, pixKeyType string) error {
	switch pixKeyType {
	case "cpf":
		// CPF key must match the player's own CPF (digits only comparison).
		cleanPlayerCPF := stripNonDigits(cpf)
		cleanPixKey := stripNonDigits(pixKey)
		if cleanPlayerCPF != cleanPixKey {
			return fmt.Errorf("CPF PIX key must match player CPF for closed-loop compliance")
		}
	case "email", "phone", "random":
		// For non-CPF keys, the key must be pre-registered in the platform.
		// In production this queries the verified_pix_keys table.
		c.logger.Info("closed loop: non-cpf key accepted with registration check",
			"cpf", maskCPF(cpf), "pix_key_type", pixKeyType)
	default:
		return fmt.Errorf("unsupported pix_key_type: %s", pixKeyType)
	}
	return nil
}

// --- helpers ---

// buildBRCode constructs a simplified PIX BR Code (Copia e Cola) string.
// Production implementations use the full EMV QR Code specification.
func buildBRCode(merchantCPFCNPJ string, amount float64, txID string) string {
	return fmt.Sprintf("00020126330014BR.GOV.BCB.PIX0111%s52040000530398654%.2f5802BR5925BETTING PLATFORM LTDA6009SAO PAULO62070503***6304ABCD",
		merchantCPFCNPJ, amount)
}

// generateTxID produces a URL-safe random transaction ID.
func generateTxID() string {
	b := make([]byte, 16)
	rand.Read(b) //nolint:errcheck
	return base64.RawURLEncoding.EncodeToString(b)
}

// generateQRCodeBase64Stub returns a placeholder base64 image.
// In production this calls a QR code generation library.
func generateQRCodeBase64Stub(data string) string {
	return base64.StdEncoding.EncodeToString([]byte(data))
}

// stripNonDigits removes all non-digit characters from a string.
func stripNonDigits(s string) string {
	result := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] >= '0' && s[i] <= '9' {
			result = append(result, s[i])
		}
	}
	return string(result)
}

// maskCPF partially masks a CPF for logging privacy.
func maskCPF(cpf string) string {
	if len(cpf) < 5 {
		return cpf
	}
	runes := []rune(cpf)
	for i := 3; i < len(runes)-2; i++ {
		if runes[i] >= '0' && runes[i] <= '9' {
			runes[i] = '*'
		}
	}
	return string(runes)
}

// abs returns the absolute value of a float64.
func abs(x float64) float64 {
	if x < 0 {
		return -x
	}
	return x
}
