http-port = 9000
http-port = ${?"HTTP_PORT"}
platform-host = ${?"PLATFORM_HOST"}
environment = ${ENVIRONMENT}

competition-labs {
  app-host = ${"COMPETITION_LABS_API_APP_HOST"}
  spaces = []

  # Per-brand configuration example:
  #
  # spaces = [{
  #   id = 79
  #   name = brandname
  #   space = brandname_staging
  #   api-key = ${CL_API_KEY}
  #   signature = ${CL_SIGNATURE}
  #   account-id = ${CL_ACCOUNT_ID}
  #   rabbit-config {
  #     host = ${RABBIT_HOST}
  #     port = 5672
  #     ssl-enabled = false
  #     queue-name = brand_events
  #     credentials {
  #       user = ${RABBIT_USER}
  #       password = ${RABBIT_PASSWORD}
  #     }
  #   }
  # }]
}

kafka {
  producer-topic = "user_awards"

  consumer-transactions {
    topic-name = "transaction"
    parallelism = 4
    batch-size = 500
    batch-time = 3 seconds
  }
  consumer-users {
    topic-name = "users"
    parallelism = 4
    batch-size = 500
    batch-time = 3 seconds
  }
  consumer-flags {
    topic-name = "flags_updates"
    parallelism = 1
    batch-size = 500
    batch-time = 3 seconds
  }

  bootstrap = ${"KAFKA_BOOTSTRAP"}
  health-check {
    delay = 3 seconds
    max-time = 5 seconds
    disabled = false
  }
}

log-events = true

kamon {
  environment {
    service = "clabs-service"
    tags {
      env = ${environment}
    }
  }
  modules {
    datadog-agent { enabled = true }
    datadog-trace-agent { enabled = true }
    datadog-api { enabled = false }
  }
}
