syntax = "proto3";

option go_package = "server";

import "google/api/annotations.proto";

// Exported interface used in the server
service PasswordHash {
  rpc hash(HashRequest) returns (HashResponse) {
    option (google.api.http) = {
      post: "/hash"
      body: "*"
    };
  }

  rpc healthCheck(Ping) returns (HealthResponse) {
    option (google.api.http) = {
      get: "/hash"
    };
  }
}

message HashRequest {
  string password = 1;
  string salt =  2;
  int32 revision = 3;
}

message HashResponse {
  bool success = 1;
  string errorMessage = 2;
  string hash = 3;
  int32 revision = 4;
}

message Ping {}

message HealthResponse {
  string status = 1;
}
