---
# Companion code for "The Backend of Luck" - Chapter 38, Case Study.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

rebuild_casino_stage_machines:
  hosts:
    acme_do_stage_gamma_brand_alpha:
      ansible_host: gamma-brandalpha.acmestage.com
      ansible_user: ansible

    acme_do_stage_beta_brand_alpha:
      ansible_host: beta-brandalpha.acmestage.com
      ansible_user: ansible

    acme_do_stage:
      ansible_host: 10.20.30.40
      ansible_user: ansible

    acme_do_stage_delta_brand_alpha:
      ansible_host: delta-brandalpha.acmestage.com
      ansible_user: ansible
