# Companion code for "The Backend of Luck" - Chapter 10, Complete Platform Architecture.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

"""
suppliers/pragmatic/provider.py
--------------------------------
Pragmatic Play — Slots + Live Casino seamless-wallet integration.

Integration model
-----------------
Pragmatic Play uses a seamless-wallet integration. The operator provides
a wallet endpoint that Pragmatic calls for every transaction. Game launches
are initiated by the operator using a signed URL with an operator-specific
secret key.

Quirks and gotchas
------------------
1. **MD5 hash authentication** — Pragmatic signs every callback using MD5
   of (sorted params + key). The operator MUST verify this hash on every
   request. Failing to verify opens the endpoint to fraudulent credits.
   MD5 is legacy; newer integrations use SHA256 but the MD5 variant is
   still the most common.

2. **Round IDs and transaction types** — Pragmatic sends:
   - `bet` — debit (player places a bet)
   - `result` — credit (round settled)
   - `refund` — reverse an unsettled bet
   - `bonusWin` — free-round credit (different action code)
   - `promoWin` — jackpot win
   A single spin may generate up to 3 separate callbacks: bet → result →
   (optionally) bonusWin.

3. **Free rounds** — Pragmatic's free-round API is a separate REST service
   (`/IntegrationService/v3/http/FreeRoundsBonusAPI/`). The operator calls
   this API to award and cancel free-round bonuses. The wallet callbacks
   during free rounds use the same bet/result flow but with amount=0 for
   the bet and non-zero for results.

4. **Currency handling** — Pragmatic sends amounts as strings with
   currency-specific decimal precision. EUR amounts have 2 decimal places,
   but JPY amounts have 0 decimal places. Always use the currency's
   configured precision when converting.

5. **Token format** — The player token is a session token generated by
   the operator at launch. Pragmatic echoes it back on every callback.
   The operator must validate that the token is still active.

6. **Error codes** — Pragmatic expects numeric error codes:
   0 = OK, 1 = Invalid token, 2 = Invalid hash, 3 = Insufficient funds,
   4 = Unknown player, 6 = Transaction already exists

API reference: https://lobby.pragmaticplay.com/en/integration-guide/
"""

from __future__ import annotations

import hashlib
import logging
from decimal import Decimal
from typing import Optional

import httpx

from accounts_provider import (
    AccountsProvider,
    CreditOperation,
    DebitOperation,
    PlayerSession,
    RefundOperation,
    SupplierOperation,
    TransactionContext,
)
from transaction_result import (
    BalanceStatus,
    TransactionResult,
    TransactionType,
    success_result,
)

logger = logging.getLogger(__name__)

SUPPLIER_ID = "pragmatic"

# Pragmatic numeric error codes
PP_OK = 0
PP_INVALID_TOKEN = 1
PP_INVALID_HASH = 2
PP_INSUFFICIENT_FUNDS = 3
PP_UNKNOWN_PLAYER = 4
PP_TRANSACTION_EXISTS = 6


def _build_hash(params: dict, secret_key: str) -> str:
    """
    Build Pragmatic Play's MD5 signature.

    The signature is computed over the sorted, concatenated key=value
    pairs plus the secret key appended at the end.

    NOTE: Pragmatic requires MD5, not SHA256. While MD5 is cryptographically
    weak, it is sufficient for message authentication when the secret key is
    strong (use at least 32 random bytes).
    """
    sorted_params = "".join(
        f"{k}{v}" for k, v in sorted(params.items()) if k not in ("hash",)
    )
    raw = sorted_params + secret_key
    return hashlib.md5(raw.encode()).hexdigest().upper()


class PragmaticProvider:
    """
    AccountsProvider implementation for Pragmatic Play.

    Handles both the slot (RNG) and live casino product lines.
    Free-rounds management is handled via a separate API client
    (not part of the core wallet flow).
    """

    def __init__(
        self,
        api_base_url: str,
        secret_key: str,
        operator_id: str,
        http_timeout_s: float = 5.0,
    ) -> None:
        self._api_base_url = api_base_url.rstrip("/")
        self._secret_key = secret_key
        self._operator_id = operator_id
        self._http_client = httpx.AsyncClient(timeout=http_timeout_s)

    async def authenticate(self, token: str) -> PlayerSession:
        """
        Validate a Pragmatic Play session token.

        Pragmatic does not provide a token validation endpoint — the
        operator is responsible for maintaining the session store.
        The token is validated by looking it up in the platform session
        cache (Redis or DB).
        """
        # In production: look up token in session cache
        # Raise AuthenticationError if not found or expired
        logger.debug("Pragmatic authenticate token=%s...", token[:16])
        from transaction_result import AuthenticationError
        # Stub — replace with real session lookup
        raise AuthenticationError("Not implemented: look up token in session store")

    def verify_hash(self, params: dict) -> bool:
        """
        Verify the MD5 hash in an inbound Pragmatic callback.

        MUST be called on every incoming request before processing.
        An invalid hash means the request is not from Pragmatic.
        """
        received_hash = params.get("hash", "")
        expected_hash = _build_hash(params, self._secret_key)
        return received_hash.upper() == expected_hash

    async def get_balance(
        self, session: PlayerSession, game_id: Optional[str] = None
    ) -> BalanceStatus:
        """
        Return balance for Pragmatic's balance callback.

        Pragmatic calls this endpoint before the first spin to verify
        the player has funds. Balance is returned in major units.
        """
        logger.debug("Pragmatic get_balance player=%s", session.player_id)
        return BalanceStatus(
            cash_balance=Decimal("0"),
            bonus_balance=Decimal("0"),
            currency=session.currency or "EUR",
        )

    async def debit(
        self,
        session: PlayerSession,
        operation: DebitOperation,
        context: TransactionContext,
    ) -> TransactionResult:
        """Process a Pragmatic `bet` callback."""
        logger.info(
            "Pragmatic BET player=%s round=%s amount=%s",
            session.player_id, operation.round_id, operation.amount,
        )
        return await self.apply_transaction(session, [operation], context)

    async def credit(
        self,
        session: PlayerSession,
        operation: CreditOperation,
        context: TransactionContext,
    ) -> TransactionResult:
        """Process a Pragmatic `result` or `bonusWin` callback."""
        logger.info(
            "Pragmatic RESULT/BONUSWIN player=%s round=%s amount=%s",
            session.player_id, operation.round_id, operation.amount,
        )
        return await self.apply_transaction(session, [operation], context)

    async def refund(
        self,
        session: PlayerSession,
        operation: RefundOperation,
        context: TransactionContext,
    ) -> TransactionResult:
        """Process a Pragmatic `refund` callback (unsettled bet rollback)."""
        logger.info(
            "Pragmatic REFUND player=%s round=%s",
            session.player_id, operation.round_id,
        )
        return await self.reverse_transaction(session, [operation], context)

    async def apply_transaction(
        self,
        session: PlayerSession,
        operations: list[SupplierOperation],
        context: TransactionContext,
    ) -> TransactionResult:
        """Apply wallet operations from a Pragmatic callback."""
        total_debit = sum(
            (op.amount for op in operations if isinstance(op, DebitOperation)), Decimal("0")
        )
        total_credit = sum(
            (op.amount for op in operations if isinstance(op, CreditOperation)), Decimal("0")
        )
        logger.debug(
            "Pragmatic apply_transaction player=%s debit=%s credit=%s",
            session.player_id, total_debit, total_credit,
        )
        balance = BalanceStatus(
            cash_balance=Decimal("0"),
            bonus_balance=Decimal("0"),
            currency=session.currency or "EUR",
        )
        tx_type = (
            TransactionType.DEBIT if total_debit > total_credit
            else TransactionType.CREDIT
        )
        return success_result(
            tx_type=tx_type,
            balance=balance,
            tx_id=context.tx_id,
            external_id=context.supplier_ref,
            cash_usage=total_debit,
        )

    async def reverse_transaction(
        self,
        session: PlayerSession,
        operations: list[SupplierOperation],
        context: TransactionContext,
    ) -> TransactionResult:
        """Reverse a Pragmatic transaction."""
        balance = BalanceStatus(
            cash_balance=Decimal("0"),
            bonus_balance=Decimal("0"),
            currency=session.currency or "EUR",
        )
        return success_result(
            tx_type=TransactionType.REFUND,
            balance=balance,
            tx_id=context.tx_id,
            external_id=context.supplier_ref,
        )

    async def award_free_rounds(
        self,
        player_id: str,
        game_id: str,
        num_rounds: int,
        currency: str,
        bet_per_round: Decimal,
    ) -> dict:
        """
        Award free rounds via Pragmatic's FRB API.

        This is a separate outbound call to Pragmatic's API, not a
        wallet callback. Used for promotional free-spin awards.

        Returns the raw API response dict.
        """
        url = f"{self._api_base_url}/IntegrationService/v3/http/FreeRoundsBonusAPI/createFRB/"
        params = {
            "secureLogin": self._operator_id,
            "playerId": player_id,
            "gameId": game_id,
            "betPerLine": str(bet_per_round),
            "numberOfRounds": str(num_rounds),
            "currency": currency,
        }
        params["hash"] = _build_hash(params, self._secret_key)
        response = await self._http_client.post(url, data=params)
        response.raise_for_status()
        return response.json()
