name = "egambling-payments"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "payments.cloud-acmetocasino.com/*", zone_name = "cloud-acmetocasino.com" }
]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "TRANSACTIONS"
database_name = "egambling-payments-txlog"
database_id = "59df7851-9285-42da-9ae2-e2f6f8c83e44"

[[kv_namespaces]]
binding = "PSP_CONFIG"
id = "9944b0e2d04c4fbca99444910d6e3521"

[observability]
enabled = true
head_sampling_rate = 1
