# Companion code for "The Backend of Luck" - Chapter 32, Testing and QA in Gambling.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

type: test
events:
  fetch_temp_homepage:
    profile:
      average_wait: 1
    transitions:
      register: 1
  register:
    profile:
      average_wait: 20
      url: /users/register/
    transitions:
      login: 1
  login:
    profile:
      average_wait: 1
      url: /users/login/
    transitions:
      get_profile: 1
  get_profile:
    profile:
      url: /users/profile/
      average_wait: 0
    transitions:
      get_config: 1
  get_config:
    profile:
      url: /main/config/
      average_wait: 0
    transitions:
      generate_geo_test_packet: 1
  generate_geo_test_packet:
    profile:
      url: /geocomply/dev_generate/
      average_wait: 0
    transitions:
      geo_validate: 1
  geo_validate:
    profile:
      url: /geocomply/validate/
      average_wait: 0
    transitions:
      homepage_landing: 1
  homepage_landing:
    profile:
      url: /offerings/homepage
      average_wait: 3
    transitions:
      deposit_funds: 1
  get_homepage:
    profile:
      url: /offerings/homepage
      average_wait: 3
    transitions:
      deposit_funds: 1
  deposit_funds:
    profile:
      url: /users/deposit/
      currency: USD
      average_wait: 10
      average: 10000
      variance: 20
    transitions:
      place_bet: 0.89
      logout: 0.1
      deposit_funds: 0.01
  place_bet:
    profile:
      average_wait: 120
      sports:
        basketball: 0.75
        ice_hockey: 0.15
        ufc_mma: 0.1
      bet_types:
        moneyline: 0.5
        over/under: 0.3
        spread: 0.1
        prop: 0.05
        future: 0.05
      straight:
        average_odds: 155
        variance_odds: 30
        average_wager: 500
        variance_wager: 2
      betslip:
        average_odds: 210
        average_size: 4
      parlay:
        rate: 0
        probability: 0.4
        total_legs: 12
        average_total_odds: 1000
        average_wager: 600
        variance_wager: 20
    transitions:
      place_bet: 0.3
      logout: 0.2
      deposit_funds: 0.1
      coupon_history: 0.4
  coupon_history:
    profile:
      average_wait: 5
    transitions:
      place_bet: 0.2
      coupon_history: 0.05
      logout: 0.2
      get_homepage: 0.45
      deposit_funds: 0.1
  logout:
    profile:
      average_wait: 0
    transitions:
      logout: 1
