feed-class=acmetocasino.feeder.progressive.ProgressiveJackpots
uploaders=["s3"]

suppliers = [
    {
        name=Blueprint
        supplier-id=63
        feed-class=acmetocasino.feeder.progressive.BlueprintJackpots
        service-url=${blueprint.service-url}
    },
    {
        name=SGDigital
        supplier-id=13
        feed-class=acmetocasino.feeder.progressive.sg.SGDigitalJackpots
        service-url=${sg_digital.service-url}
        api-version=1.4
        ogs-operator-id=202
        supported-currencies=["AUD", "BGN", "BRL", "CAD", "CHF", "CNY", "CZK", "DKK", "EUR", "GBP", "HKD", "HRK", "HUF", "INR", "ISK", "JPY", "MXN", "MYR", "NOK", "NZD", "PLN", "RON", "RUB", "SEK", "SGD", "THB", "TRY", "USD", "ZAR"]
    },
    {
        name=Evolution
        supplier-id=29
        feed-class=acmetocasino.feeder.progressive.EvolutionJackpots
        service-url=${evo.service-url}
    },
    {
        name=MGS
        supplier-id=21
        feed-class=acmetocasino.feeder.progressive.MGSJackpots
        service-url=${mgs.service-url}
    },
    {
        name=Leander
        supplier-id=14
        operator-id=${leander.operator-id}
        feed-class=acmetocasino.feeder.progressive.LeanderJackpots
        service-url=${leander.service-url}
    },
    {
        name=Stakelogic
        supplier-id=66
        partner-id-mga=59
        partner-id-ukgc=59
        feed-class=acmetocasino.feeder.progressive.StakelogicJackpots
        service-url=${stakelogic.service-url}
    }
]
