---
# Companion code for "The Backend of Luck" - Chapter 23, DevSecOps for iGaming.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

nj_c8_machines:
  hosts:
    nj_db_1:
      ansible_host: 203.0.113.114
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_db_2:
      ansible_host: 203.0.113.115
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_master_1:
      ansible_host: 203.0.113.109
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_master_2:
      ansible_host: 203.0.113.110
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_master_3:
      ansible_host: 203.0.113.111
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_worker_1:
      ansible_host: 203.0.113.103
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_worker_2:
      ansible_host: 203.0.113.104
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_worker_3:
      ansible_host: 203.0.113.105
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_worker_4:
      ansible_host: 203.0.113.106
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    nj_worker_5:
      ansible_host: 203.0.113.107
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

    ## nj-platform.live.acmetocasino.com
    nj_worker_6: ## NJ Production Platform Host ##
      ansible_host: 203.0.113.108
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible-dc

  children:
    nj_k8s_masters:
      hosts:
        nj_master_1:
        nj_master_2:
        nj_master_3:

    nj_k8s_nodes:
      hosts:
        nj_worker_1:
        nj_worker_2:
        nj_worker_3:
        nj_worker_4:
        nj_worker_5:
        nj_worker_6:
    nj_dbs:
      hosts:
        nj_db_1:
        nj_db_2:
