env {
  stage {
    db {
      platform {
        driver: "oracle.jdbc.OracleDriver"
        url: "jdbc:oracle:thin:@dbhost-stage:1521:ora1"
        user: "casino_core"
        password = "${PLATFORM_DB_PASSWORD}"
      }
      cms {
        driver: "com.mysql.jdbc.Driver"
        url: "jdbc:mysql://localhost/acme_cms"
        user: "acme_cms"
        password: "${CMS_DB_PASSWORD}"
      }
    }
  }

  prod {
    db {
      platform: {
        driver: "oracle.jdbc.OracleDriver"
        url: "jdbc:oracle:thin:@dbhost-prod:1521:pdb"
        user: "casino_core"
        password = "${PLATFORM_DB_PASSWORD}"
      }
      cms {
        driver: "com.mysql.jdbc.Driver"
        url: "jdbc:mysql://localhost/acme_cms"
        user: "acme_cms"
        password: "${CMS_DB_PASSWORD}"
      }
    }
  }
}

smtp {
  server {
    host = "mail.acmetocasino.com"
    port = 587
  }

  tls = false

  auth {
    username = "no-reply@acmetocasino.com"
    password = "${SMTP_PASSWORD}"
  }

  headers {
    foo = "bar"
  }
}

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
}
