input {
	beats {
		port => 5044
	}

	tcp {
		port => 5000
	}

	file {
          path => "/usr/share/logstash/logs/**/*.log"
		  codec => json
		  start_position => beginning
    }
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
		ecs_compatibility => disabled
	}
}
