#!/usr/bin/env bash
# Companion code for "The Backend of Luck" - Chapter 20b, OpenBao Operations.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

# Configure the database secrets engine against a PostgreSQL test container.
# Creates both a dynamic `readonly` role and a static `app-writer` role.
#
# Prerequisites:
#   - PostgreSQL 14+ reachable at $PG_HOST:$PG_PORT with a superuser that can
#     CREATE ROLE and GRANT privileges on the target database.
#   - The openbao sandbox running (start-sandbox.sh).
#
# This does not touch any production database. The defaults point at the
# pg18-hsm-test container's exposed port on ops-host if you override PG_HOST
# explicitly; by default it stays on 127.0.0.1 and you are expected to
# tunnel or port-forward manually.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"

: "${PG_HOST:=127.0.0.1}"
: "${PG_PORT:=5432}"
: "${PG_DB:=casino_sandbox}"
: "${PG_SUPER:=postgres}"
: "${PG_SUPER_PASS:?PG_SUPER_PASS must be set in the environment (do NOT hard-code)}"
: "${BAO_DB_USER:=bao_root}"
: "${BAO_DB_PASS:?BAO_DB_PASS must be set in the environment (generated by the caller)}"

ensure_sandbox
load_root_token
require_cmd psql

export PGPASSWORD="$PG_SUPER_PASS"

log "bootstrapping bao_root user on $PG_HOST:$PG_PORT/$PG_DB"
psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_SUPER" -d postgres -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '$BAO_DB_USER') THEN
    CREATE ROLE "$BAO_DB_USER" WITH LOGIN PASSWORD '$BAO_DB_PASS' CREATEROLE;
  END IF;
END
\$\$;
SELECT 'ensure database exists'
 WHERE EXISTS (SELECT 1 FROM pg_database WHERE datname = '$PG_DB');
SQL

psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_SUPER" -d postgres -v ON_ERROR_STOP=1 -c \
  "SELECT 1 FROM pg_database WHERE datname = '$PG_DB'" | grep -q 1 \
  || psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_SUPER" -d postgres -v ON_ERROR_STOP=1 -c \
     "CREATE DATABASE $PG_DB OWNER $BAO_DB_USER"

unset PGPASSWORD

# Enable the engine
if ! "$BAO_BIN" secrets list -format=json | python3 -c 'import json,sys; print("database/" in json.load(sys.stdin))' | grep -q True; then
  log "enabling database engine"
  "$BAO_BIN" secrets enable database
else
  log "database engine already enabled"
fi

# Configure the connection
log "configuring database/config/casino"
"$BAO_BIN" write database/config/casino \
  plugin_name=postgresql-database-plugin \
  connection_url="postgresql://{{username}}:{{password}}@${PG_HOST}:${PG_PORT}/${PG_DB}?sslmode=prefer" \
  allowed_roles="readonly,app-writer" \
  username="$BAO_DB_USER" \
  password="$BAO_DB_PASS"

# Rotate the root credential so nobody -- including this script's environment --
# can log in as bao_root anymore.
log "rotating bao_root password (original becomes unusable)"
"$BAO_BIN" write -f database/rotate-root/casino

# Dynamic role: readonly
log "creating dynamic role 'readonly'"
"$BAO_BIN" write database/roles/readonly \
  db_name=casino \
  creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
    GRANT CONNECT ON DATABASE $PG_DB TO \"{{name}}\";
    GRANT USAGE ON SCHEMA public TO \"{{name}}\";
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{name}}\";" \
  default_ttl="1h" \
  max_ttl="24h"

# Static role: app-writer (pre-existing user that OpenBao rotates)
if [[ "${CREATE_STATIC_USER:-0}" == "1" ]]; then
  log "creating static-role target user 'app_writer'"
  PGPASSWORD="$PG_SUPER_PASS" psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_SUPER" -d "$PG_DB" -v ON_ERROR_STOP=1 -c "
    CREATE ROLE app_writer WITH LOGIN PASSWORD 'bootstrap-to-be-rotated';
    GRANT CONNECT ON DATABASE $PG_DB TO app_writer;
    GRANT USAGE ON SCHEMA public TO app_writer;
    GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_writer;
  " || log "(app_writer may already exist)"
fi

"$BAO_BIN" write database/static-roles/app-writer \
  db_name=casino \
  username=app_writer \
  rotation_period=24h \
  rotation_statements="ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"

log "issuing a sample dynamic readonly credential"
"$BAO_BIN" read database/creds/readonly

log "fetching static app-writer credential"
"$BAO_BIN" read database/static-creds/app-writer
