#!/usr/bin/env bash
# Companion code for "The Backend of Luck" - Chapter 20b, OpenBao Operations.
# https://thebackendofluck.com | https://github.com/thebackendofluck/book
# SPDX-License-Identifier: Apache-2.0
#
# FOR TESTING AND EVALUATION ONLY. NOT FOR PRODUCTION USE.
# Published to demonstrate the patterns explained in the book. This code is
# not certified for real-money gaming: operating a gambling platform requires
# your own licence, independent test-lab certification (GLI, eCOGRA or
# equivalent) and regulator approval.

# Issue a short-lived leaf certificate from the sandbox PKI and verify its
# chain against the root CA generated by pki-setup.sh.
#
# Usage: pki-issue-cert.sh [common-name] [ttl]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"

CN=${1:-wallet.internal.acme}
TTL=${2:-1h}

ensure_sandbox
load_root_token
require_cmd openssl

OUT_DIR="${SANDBOX_DIR}/pki-out"
[[ -f "$OUT_DIR/root.crt" ]] || die "run pki-setup.sh first -- root.crt not found"

log "issuing certificate for $CN with ttl=$TTL"
json=$("$BAO_BIN" write -format=json pki_int/issue/internal-service \
  common_name="$CN" ttl="$TTL")

echo "$json" | python3 -c '
import json, sys, pathlib
d = json.load(sys.stdin)["data"]
out = pathlib.Path(sys.argv[1])
(out / "leaf.crt").write_text(d["certificate"] + "\n")
(out / "leaf.key").write_text(d["private_key"] + "\n")
(out / "leaf.chain.crt").write_text(d["certificate"] + "\n" + "\n".join(d["ca_chain"]) + "\n")
print("serial:", d["serial_number"])
' "$OUT_DIR"

log "verifying chain"
openssl verify -CAfile "$OUT_DIR/root.crt" -untrusted "$OUT_DIR/intermediate.crt" "$OUT_DIR/leaf.crt"

log "certificate details"
openssl x509 -in "$OUT_DIR/leaf.crt" -noout -subject -issuer -dates -serial
